import React from 'react';
import { MainNav } from '@/components/MainNav';
import Head from 'next/head';

interface IProps {
  children: React.ReactNode;
}

export const Layout: React.FC<IProps> = (props) => {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <MainNav />
      <div className="flex justify-center items-center ">{props.children}</div>
    </section>
  );
};
