import { MainNav } from '@/components/MainNav';
import Head from 'next/head';

export const Layout = (props) => {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <MainNav />
      <div>{props.children}</div>
    </section>
  );
};
